version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: personal_blog_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      docker-php-ext-install pdo pdo_mysql &&
      a2enmod rewrite &&
      echo '<VirtualHost *:80>
        DocumentRoot /var/www/html/public
        <Directory /var/www/html/public>
          AllowOverride All
          Require all granted
        </Directory>
      </VirtualHost>' > /etc/apache2/sites-available/000-default.conf &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    container_name: personal_blog_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_blog
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: blog_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: personal_blog_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data:
